name: tokens
on: [push, pull_request]
jobs:
  list-tokens:
    runs-on: ubuntu-latest
    outputs:
      tokens: ${{ steps.set-tokens.outputs.tokens }}
    steps:
      - uses: actions/checkout@v2
      - id: set-tokens
        run: echo "::set-output name=tokens::$(ls tokens | jq -R -s -c 'split("\n")[:-1]')"
  list-token-components:
    needs: list-tokens
    runs-on: ubuntu-latest
    strategy:
        matrix:
            token: ${{ fromJson(needs.list-tokens.outputs.tokens) }}
    steps:
      - uses: actions/checkout@v2   
      - run: echo "Building token ${{ matrix.token }}."