name: tokens
on: [push, pull_request]
jobs:
  get-manifest:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.set-manifest.outputs.manifest }}
    steps:
      - uses: actions/checkout@v2
      - id: set-manifest
        run: python3 create_target_matrix.py >> $GITHUB_OUTPUT
  compile:
    needs: get-manifest
    runs-on: ubuntu-latest
    strategy:
        matrix: ${{fromJson(needs.get-manifest.outputs.manifest)}}
    env:
      BUILD_DIR: "build"
      BUILD_TARGET_DIR: "${BUILD_DIR}/${{ matrix.target }}"
      BUILD_OUTPUT: "${BUILD_TARGET_DIR}/${{ matrix.component }}.stl"
      BUILD_INPUT: "target/${{ matrix.target }}/${{ matrix.component }}.scad"
    steps:
      - name: Install Openscad
        run: |
          sudo apt update
          sudo apt install -y openscad
      - uses: actions/checkout@v2   
      - run: mkdir -p build/${{ matrix.target }}
      - name: Compile Component
        run: openscad -o "build/${{ matrix.target }}/${{ matrix.component }}.stl" "target/${{ matrix.target }}/${{ matrix.component }}.scad"
      - name: Archive Compiled STL Files
        uses: actions/upload-artifact@v4
        with:
          name: build/${{ matrix.target }}/${{ matrix.component }}.stl
          path: |
            build/${{ matrix.target }}/${{ matrix.component }}.stl

