name: tokens
on: [push, pull_request]
jobs:
  list-tokens:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls tokens | jq -R -s -c 'split("\n")[:-1]')"
  check:
    needs: list-tokens
    runs-on: ubuntu-latest
    strategy:
        matrix:
            token: ${{ fromJson(needs.list-tokens.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      - run: echo "Building token ${{ matrix.token }}."