name: tokens
on: [push, pull_request]
jobs:
  get-manifest:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.set-manifest.outputs.manifest }}
    steps:
      - uses: actions/checkout@v2
      - id: set-manifest
        run: echo "manifest=$(python3 create_target_matrix.py) >> $GITHUB_OUTPUT
  list-token-components:
    needs: get-manifest
    runs-on: ubuntu-latest
    strategy:
        matrix:
            include: ${{fromJson(needs.get-maanifest.outputs.manifest)}}
    steps:
      - uses: actions/checkout@v2   
      - run: echo "target ${{ matrix.target }} component ${{ matrix.component }}"

