name: tokens
on: [push, pull_request]
jobs:
  list-tokens:
    runs-on: ubuntu-latest
    outputs:
      tokens: ${{ steps.set-tokens.outputs.tokens }}
    steps:
      - uses: actions/checkout@v2
      - id: set-tokens
        run: echo "::set-output name=tokens::$(ls tokens | jq -R -s -c 'split("\n")[:-1]')"
  list-token-components:
    needs: list-tokens
    runs-on: ubuntu-latest
    strategy:
        matrix:
            token: ${{ fromJson(needs.list-tokens.outputs.tokens) }}
    outputs:
      components: ${{ steps.set-components.outputs.components }}
    steps:
      - uses: actions/checkout@v2   
      - id: set-components
        run: echo "::set-output name=components::$(ls tokens/${{ matrix.token }} | jq -R -s -c 'split("\n")[:-1]')"
  compile:
    needs: list-token-components
    runs-on: ubuntu-latest
    strategy:
        matrix:
            component: ${{ fromJson(needs.list-token-components.outputs.components) }}
    steps:
      - uses: actions/checkout@v2   
      - run: echo "token ${{ matrix.component }}"
