name: tokens
on: [push, pull_request]
jobs:
  get-manifest:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.set-manifest.outputs.manifest }}
    steps:
      - uses: actions/checkout@v2
      - id: set-manifest
        run: python3 create_target_matrix.py >> $GITHUB_OUTPUT
  compile:
    needs: get-manifest
    runs-on: ubuntu-latest
    strategy:
        matrix: ${{fromJson(needs.get-manifest.outputs.manifest)}}
    env:
      BUILD_DIR: build
      BUILD_TARGET_DIR: ${BUILD_DIR}/${{ matrix.target }}
      BUILD_OUTPUT: ${BUILD_TARGET_DIR}/${{ matrix.component }}.stl
      BUILD_INPUT: target/${{ matrix.target }}/${{ matrix.component }}.scad
    steps:
      - uses: actions/checkout@v2   
      - run: mkdir -p $BUILD_TARGET_DIR
      - uses: pkoehlers/openscad-build-action@v1
        with:
          input-file: $BUILD_INPUT
          output-file: $BUILD_OUTPUT
      - name: Archive Compiled STL Files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build

